-- Baseline migration: captures the schema exactly as Hibernate's ddl-auto=update had already
-- built it in every existing environment (see application.properties for why baseline-on-migrate
-- is what lets those environments adopt Flyway without Flyway trying, and failing, to re-create
-- tables that already exist). A brand new database - a fresh Testcontainers container in CI, a
-- new environment - runs this from scratch and ends up with the identical schema.
--
-- Constraints are explicitly named throughout (rather than left to Postgres's or Hibernate's
-- auto-naming) so a future migration can reference them unambiguously (e.g. "ALTER TABLE ...
-- DROP CONSTRAINT fk_accounts_owner").

CREATE TABLE app_users
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username      VARCHAR(255) NOT NULL,
    email         VARCHAR(255) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    display_name  VARCHAR(255),
    role          VARCHAR(255) NOT NULL,
    enabled       BOOLEAN      NOT NULL,
    created_at    TIMESTAMP(6) NOT NULL,
    CONSTRAINT uq_app_users_username UNIQUE (username),
    CONSTRAINT uq_app_users_email UNIQUE (email)
);

CREATE TABLE customers
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name          VARCHAR(255) NOT NULL,
    email         VARCHAR(255) NOT NULL,
    phone         VARCHAR(255),
    customer_type VARCHAR(20),
    CONSTRAINT uq_customers_email UNIQUE (email),
    CONSTRAINT chk_customers_customer_type CHECK (customer_type IN ('B2C', 'B2B', 'LEGACY'))
);

CREATE TABLE orders
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id BIGINT           NOT NULL,
    product     VARCHAR(255)     NOT NULL,
    amount      DOUBLE PRECISION NOT NULL,
    order_date  TIMESTAMP(6)     NOT NULL,
    CONSTRAINT fk_orders_customer FOREIGN KEY (customer_id) REFERENCES customers (id)
);

CREATE TABLE accounts
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_id   BIGINT         NOT NULL,
    currency   VARCHAR(3)     NOT NULL,
    balance    NUMERIC(19, 2) NOT NULL,
    created_at TIMESTAMP(6)   NOT NULL,
    CONSTRAINT fk_accounts_owner FOREIGN KEY (owner_id) REFERENCES app_users (id),
    CONSTRAINT chk_accounts_balance_non_negative CHECK (balance >= 0)
);

CREATE TABLE operations
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id        BIGINT         NOT NULL,
    type              VARCHAR(20)    NOT NULL,
    amount            NUMERIC(19, 2) NOT NULL,
    balance_after     NUMERIC(19, 2) NOT NULL,
    transfer_group_id VARCHAR(36),
    created_at        TIMESTAMP(6)   NOT NULL,
    CONSTRAINT fk_operations_account FOREIGN KEY (account_id) REFERENCES accounts (id),
    CONSTRAINT chk_operations_type CHECK (type IN ('DEPOSIT', 'WITHDRAWAL', 'TRANSFER_OUT', 'TRANSFER_IN'))
);

CREATE TABLE idempotency_records
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    idempotency_key   VARCHAR(100) NOT NULL,
    owner_username    VARCHAR(255) NOT NULL,
    operation_id      BIGINT,
    transfer_group_id VARCHAR(36),
    created_at        TIMESTAMP(6) NOT NULL,
    CONSTRAINT uq_idempotency_records_key UNIQUE (idempotency_key)
);

-- Spring Session JDBC's own schema (normally auto-applied via spring.session.jdbc.initialize-
-- schema=always - disabled in application.properties now that this migration owns it instead),
-- copied from org/springframework/session/jdbc/schema-postgresql.sql so every table in this
-- database, third-party ones included, is versioned through one migration history.
CREATE TABLE spring_session
(
    primary_id            CHAR(36)     NOT NULL,
    session_id            CHAR(36)     NOT NULL,
    creation_time         BIGINT       NOT NULL,
    last_access_time      BIGINT       NOT NULL,
    max_inactive_interval INT          NOT NULL,
    expiry_time           BIGINT       NOT NULL,
    principal_name        VARCHAR(100),
    CONSTRAINT pk_spring_session PRIMARY KEY (primary_id)
);

CREATE UNIQUE INDEX spring_session_ix1 ON spring_session (session_id);
CREATE INDEX spring_session_ix2 ON spring_session (expiry_time);
CREATE INDEX spring_session_ix3 ON spring_session (principal_name);

CREATE TABLE spring_session_attributes
(
    session_primary_id CHAR(36)     NOT NULL,
    attribute_name      VARCHAR(200) NOT NULL,
    attribute_bytes      BYTEA        NOT NULL,
    CONSTRAINT pk_spring_session_attributes PRIMARY KEY (session_primary_id, attribute_name),
    CONSTRAINT fk_spring_session_attributes_session FOREIGN KEY (session_primary_id)
        REFERENCES spring_session (primary_id) ON DELETE CASCADE
);
