-- The transactional outbox. Solves the dual-write problem: "append the ledger row AND tell the
-- outside world about it" is two writes to two different systems (Postgres, and whatever broker
-- publishes the event), and there is no way to make two systems commit atomically without a
-- distributed transaction. Whichever order you attempt them in, a crash in the gap leaves the two
-- disagreeing forever - a ledger row nobody was told about, or an event about a transfer that was
-- rolled back and never happened.
--
-- The outbox removes the second system from the write path entirely. AccountMutationExecutor
-- inserts the event HERE, in the same local transaction that moves the money, so the event and the
-- balance change are one atomic commit - either both are durable or neither is. A separate poller
-- (OutboxRelay) reads committed rows afterwards and does the publishing. The publish can now fail,
-- retry, and be duplicated freely, because it is no longer entangled with the money.
--
-- What this buys is at-least-once delivery, never exactly-once: the relay can publish successfully
-- and then crash before marking the row PUBLISHED, and the next poll will publish it again. That
-- is not a flaw to be fixed here - it is inherent, and the fix belongs on the consumer, which must
-- be idempotent. This codebase already has the consumer-side version of that idea in
-- idempotency_records.

CREATE TABLE outbox_messages
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- What the event is about, kept as (type, id) rather than a foreign key: an outbox row is a
    -- historical fact about something that happened, and it must stay readable and publishable
    -- even if the row it describes is later archived away. A real FK would couple the two
    -- lifecycles and let a cascade delete silently drop undelivered events.
    aggregate_type  VARCHAR(50)  NOT NULL,
    aggregate_id    VARCHAR(64)  NOT NULL,
    event_type      VARCHAR(50)  NOT NULL,
    payload         TEXT         NOT NULL,
    status          VARCHAR(20)  NOT NULL,
    attempts        INTEGER      NOT NULL DEFAULT 0,
    -- When this row next becomes eligible to be claimed. Set to now() on insert, and pushed into
    -- the future by exponential backoff after each failed dispatch, so a broker that is down does
    -- not get hammered once per poll by every pending row at once.
    next_attempt_at TIMESTAMP(6) NOT NULL,
    last_error      VARCHAR(500),
    created_at      TIMESTAMP(6) NOT NULL,
    published_at    TIMESTAMP(6),
    CONSTRAINT chk_outbox_messages_status CHECK (status IN ('PENDING', 'PUBLISHED', 'DEAD'))
);

-- Partial index, deliberately: the relay only ever asks one question - "which PENDING rows are due
-- now, oldest first?" - and a full index over every row would keep growing with the PUBLISHED
-- history that query never touches. Restricting it to status = 'PENDING' means the index stays
-- roughly the size of the backlog (normally near zero) rather than the size of the table, and rows
-- drop out of it as they are published rather than accumulating in it forever.
CREATE INDEX idx_outbox_messages_claimable
    ON outbox_messages (next_attempt_at, id)
    WHERE status = 'PENDING';
